#!/bin/sh /etc/rc.common
START=92
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/wemo-commissioning-watcher
  procd_set_param respawn  # restart if it crashes before we commission
  procd_close_instance
}

