#!/bin/sh
# IMPORTANT : trigger switch will kill this pid if
# buton release is seen.
# Start: Interfaces with WiFi LED Status Control
# state:
#        1: Booting - Slow Blink - RGB 1 White
#        2: Ready to Connect - Slow Blink - RGB 1 Blue
#        3: Identify Hardware (HomeKit) - Fast Blink - RGB 1 Green
#        4: Connection Found - Solid 100% - #4A - RGB 1 White / #4B - RGB 1 Blue
#        5: Turn on - Solid 100% - RGB 1 White
#        6: Turn off - Dimmed - White LED 1
#        7. Power Button Control - Fast Blink - RGB 1 Green
#        8. Schedule Rule - solid 100% - RGB 1 Green
#        9. Auto Off Timer Rule - solid 100% / slow blink to fast blink  - RGB 1 Green
#        10. Long Press Rule - Fast Blink - RGB 1 Green
#        11. Away Rule - solid 100% - RGB 1 Green
#        12. Service Integration - Fast Blink - RGB 1 Green
#        131. Error Detected - Solid 100%- RGB 1 Red
#        132. Error Detected - Slow Blink- RGB 1 Red
#        141. Slow white blink
#        142. Slow Blue blink
#        143. Slow Red blink
#        15. Firmware Update - low Blink - LED 1

echo $$ > /tmp/resetwifi.pid

pwm=/sys/class/pwm/pwmchip0/pwm1/period
pwm_saved=$(cat /sys/class/pwm/pwmchip0/pwm1/period)


cleanup() {
    echo 2 > $pwm
    rm -f /tmp/resetwifi.pid
    exit
}


sleep 2
#install trap only if we are going to change leds
trap cleanup SIGHUP SIGINT SIGTERM
echo 2 > $pwm
sleep 3

# Let's steal the gpio control from gpio-button-hotplug
rmmod gpio_button_hotplug
# Check if gpio22 is still pressed
echo 22 > /sys/class/gpio/export
if [ $(cat /sys/class/gpio/gpio22/value) -eq 1 ];then
    # button released, no action required.
    # give back the gpio22 control back to gpio-button-hotplug
    echo 22 > /sys/class/gpio/unexport
    modprobe gpio-button-hotplug
    echo $pwm_saved > $pwm
    exit 0
fi

rm -f /tmp/resetwifi.pid
# now we passed the timer, we will reset wifi...
echo 6 > $pwm
sleep 3
echo 4 > $pwm
sleep 1.5
echo 9 > $pwm

logger "WIFI Resetting..."
/sbin/nvram_set wemo_ipaddr=
/sbin/nvram_set restore_state=1
/sbin/nvram_set ClientSSID=
killall wemoApp

ifconfig apcli0 down
ifconfig ra0 down
rmmod mt7628
sleep 1
modprobe mt7628

# restore gpio-button-hotplug
echo 22 > /sys/class/gpio/unexport

modprobe gpio-button-hotplug
cleanup
