#!/bin/sh /etc/rc.common

START=70

start() {
   # Check to see if the unit is configured by
   # retrieving ClientSSID in nvram.
   nvram_clientssid=`nvram_get ClientSSID | cut -f2 -d=`
   if [ "${nvram_clientssid}x" != "x" ]; then
       # if ClientSSID is there, we will bring down AP mode
       /sbin/ifconfig apcli0 up
       iwpriv ra0 set airplayEnable=0
       /sbin/ifconfig ra0 down
   else
       /sbin/ifconfig ra0 up
       iwpriv ra0 set airplayEnable=1
   fi

   # create startup flag file.  wemoApp must delete this file
   # when it has determined that it is running correctly.
   # this is used as a flag by the firmware update subsystem
   # to determine if an roll back is needed or not.
   touch /tmp/wemoApp.starting

   fw_printenv boot_A_args > /tmp/bootArgs

   sh /sbin/startWemo.sh &
}

stop() {
   wemoPid=`ps | awk '/sbin\/startWemo/ {print $1}'`
   kill -9 $wemoPid
   killall wemoApp
   nvram commit
   killall nvramd
   #Magic Close of watchdog after App stops to prevent system reboot due to watchdog.
   echo "V" >/dev/watchdog
}
